sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 172.28.169.5
    port: 3306
    database: TAKEOUT
    username: PHERO
    password: 4617
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5tQ1FTn73MmcfxNLyupp
    access-key-secret: cgEycvdcKQa0AK7oXe5NWVmyYObpR5
    bucket-name: fq-take-out
