sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 172.28.169.5
    port: 3306
    database: TAKEOUT
    username: PHERO
    password: 4617
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    accessKeyId: LTAI5tQ1FTn73MmcfxNLyupp
    accessKeySecret: cgEycvdcKQa0AK7oXe5NWVmyYObpR5
    bucketName: fq-take-out
  redis:
    host: localhost
    port: 6379
    database: 1
  wechat:
    appid: wx5a8c8c83ba137763
    secret: cd2c65446171f5a620bd87407a3371fb
